[[answers]]
fraction = 100
text = "Definitely not right."
feedback = "Wow, You got it..."

[[answers]]
fraction = 50
text = "Maybe this is right?"
feedback = "Are you sure?"

[[answers]]
fraction = 25
text = "This is right"
feedback = "No it's not"
