[[testcases]]
example = true
display = '''SHOW'''
testcode = ''''''
stdin = '''12.5
5.5'''
expected ='''Enter the base of the rectangle in centimetres: 12.5
Enter the height of the rectangle in centimetres: 5.5
The area of the rectangle is 68.75cm^2'''

[[testcases]]
example = true
display = '''SHOW'''
testcode = ''''''
stdin = '''100
200'''

[[testcases]]
example = true
display = '''SHOW'''
testcode = ''''''
stdin = '''0
10'''
expected ='''Enter the base of the rectangle in centimetres: 0
Enter the height of the rectangle in centimetres: 10
The area of the rectangle is 0.00cm^2'''