[[answers]]
fraction = 100
text = "Asma :)"
feedback = "Yes she is!!!"

[[answers]]
fraction = 75
text = "James"
feedback = "I'm sure he's great!"

[[answers]]
fraction = 0
text = "Carl. T"
feedback = "No he's not even a lecturer"